app/__init__.py
from flask import Flask, render_template
from .site.routes import site
from .auth.routes import auth
from .api.routes import api
from config import Config

from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from models import db as root_db, login_manager, ma
from flask_cors import CORS
from helpers import JSONEncoder

app = Flask(__name__)
CORS(app)

app.register_blueprint(site)
app.register_blueprint(auth)
app.register_blueprint(api)

app.json_encoder = JSONEncoder
app.config.from_object(Config)
root_db.init_app(app)
login_manager.init_app(app)
ma.init_app(app)
migrate = Migrate(app, root_db)

@app.errorhandler(404)
def page_not_found(e):
    return render_template("index.html")

app/api/routes.py
from flask import Blueprint, request, jsonify, render_template
from helpers import token_required
from models import db, User, Entry, entry_schema, entries_schema
from flask_login import current_user

api = Blueprint('api',__name__, url_prefix='/api')

@api.route('/entries', methods=['POST'])
@token_required
def create_entry(current_user):
    name = request.json['name']
    details = request.json['details']
    user_id = current_user.id

    entry = Entry(name=name, details=details, user_id=user_id)

    db.session.add(entry)
    db.session.commit()

    response = entry_schema.dump(entry)
    return jsonify(response)

@api.route('/entries', methods = ['GET'])
@token_required
def get_entry(current_user):
    a_user = current_user.id
    entry = Entry.query.filter_by(user_id = a_user).all()
    response = entries_schema.dump(entry)
    return jsonify(response)

app/site/routes.py
from flask import Blueprint, render_template

site = Blueprint('site', __name__, template_folder='site_templates')

@site.route('/')
def home():
    return render_template('index.html')

@site.route('/profile')
def profile():
    return render_template('profile.html')

@site.route('/ceremonies')
def ceremonies():
    return render_template('ceremonies.html')

@site.route('/dieties')
def dieties():
    return render_template('dieties.html')

@site.route('/herbs')
def herbs():
    return render_template('herbs.html')

@site.route('/holidays')
def holidays():
    return render_template('holidays.html')

@site.route('/journal')
def journal():
    return render_template('journal.html')

@site.route('/spells')
def spells():
    return render_template('spells.html')

@site.route('/symbols')
def symbols():
    return render_template('symbols.html')

@site.route('/tools')
def tools():
    return render_template('tools.html')

app/templates/addbutton.html
<div id="addbutton">
    <button class="btn text-light rounded-circle p-0 m-0">
        <svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" fill="currentColor" class="bi bi-plus-circle p-0 m-0" viewBox="0 0 16 16">
            <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
            <path d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4z"/>
        </svg>
    </button>
</div>

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<meta name="Description" content="Enter your description here"/>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.0/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
<link rel="stylesheet" href="../static/style.css">
<script src="../static/main.js"></script>

<title>My Grimoire</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark">
        <div class="container-fluid">
            <a href="{{ url_for('site.home') }}" class="navbar-brand order-1 order-lg-0 mx-lg-3">My Grimoire</a>
            {% if current_user.is_authenticated %}
            <button 
                class="navbar-toggler order-0 black" 
                type="button" 
                data-bs-toggle="collapse" 
                data-bs-target="#navMenu" 
                aria-controls="navbarScroll" 
                aria-expanded="false" 
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse black" id="navMenu">
                <ul class="navbar-nav m-auto">
                    <li class="nav-item mx-3">
                        <a href="{{ url_for('site.dieties') }}" class="nav-link">Dieties</a>
                    </li>
                    <li class="nav-item mx-3">
                        <a href="{{ url_for('site.herbs') }}" class="nav-link">Herbs</a>
                    </li>
                    <li class="nav-item mx-3">
                        <a href="{{ url_for('site.spells') }}" class="nav-link">Spells</a>
                    </li>
                    <li class="nav-item mx-3">
                        <a href="{{ url_for('site.holidays') }}" class="nav-link">Holidays</a>
                    </li>
                    <li class="nav-item mx-3">
                        <a href="{{ url_for('site.ceremonies') }}" class="nav-link">Ceremonies</a>
                    </li>
                    <li class="nav-item mx-3">
                        <a href="{{ url_for('site.tools') }}" class="nav-link">Tools</a>
                    </li>
                    <li class="nav-item mx-3">
                        <a href="{{ url_for('site.symbols') }}" class="nav-link">Symbols</a>
                    </li>
                    <li class="nav-item mx-3">
                        <a href="{{ url_for('site.journal') }}" class="nav-link">Journal</a>
                    </li>
                </ul>
            </div>
            <a href="{{ url_for('site.profile') }}" class="navbar-brand order-2 mx-lg-3">Me</a>
            {% else %}
            <div class="order-2">
                <a href="{{ url_for('auth.signin') }}" class="navbar-brand mx-lg-3">Sign In</a>
                <a href="{{ url_for('auth.signup') }}" class="navbar-brand mx-lg-3">Sign Up</a>
            </div>
            {% endif %}
        </div>
    </nav>

    {% block content %}
    {% endblock %}

<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.9.2/umd/popper.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.0/js/bootstrap.min.js"></script>
</body>
</html>

app/templates/signinform.html
<div class="container col-lg-6">
    <div class="">
        <form method="POST">
            {{ form.hidden_tag() }}
            <div class="mb-3">
                {{ form.username.label }}
                {{ form.username(class = 'form-control', placeholder = 'Username') }}
            </div>
            <div class="mb-3">
                {{ form.password.label }}
                {{ form.password(class = "form-control", placeholder = "Password") }}
            </div>
            {{ form.submit_button(class = "btn btn-primary btn-block mt-2")}}
        </form>
    </div>
</div>

app/templates/signupform.html
<form method="POST">
    {{ form.hidden_tag() }}
    <fieldset id="username-field">
        {{ form.username.label }}
        {{ form.username(class = 'form-control', placeholder = 'Username') }}
    </fieldset>
    <fieldset id="email-field">
        {{ form.email.label }}
        {{ form.email(class = 'form-control', placeholder = 'Email') }}
    </fieldset>
    <fieldset id="pass-field"> 
        {{ form.password.label }}
        {{ form.password(class = "form-control", placeholder = "Password") }}
    </fieldset>
    {{ form.submit_button(class = "btn btn-primary btn-block mt-2")}}
</form>